name: stace_x_providers
description: presebtation layer for SpaceX.
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_launcher_icons: ^0.9.2
  json_annotation:
  freezed:
  logging:


  provider: ^6.0.1




# For UIs
  cached_network_image: ^3.1.0+1
  photo_view: ^0.13.0
  mailto: ^2.0.0
  slide_countdown: ^0.0.7
  youtube_player_iframe: ^2.2.2
  url_launcher: ^6.0.15
  flutter_spinkit: ^5.1.0
  flutter_localizations:
    sdk: flutter


# For DI
  get_it: ^7.2.0



  fluro: ^2.0.3
  build_runner: ^2.1.5
  flutter_form_builder: ^7.0.0

  pull_to_refresh: ^2.0.0
  another_flushbar: ^1.10.26
  data:
    path: ../data
  domain:
    path: ../domain


  # For Splash screen
  flutter_native_splash: ^1.3.1
# setting app icons
flutter_icons:
  #  image_path: "assets/images/launcher_icon/icon-128x128.png"
  image_path_android: "assets/images/launcher_icon/launch.png"
  image_path_ios: "assets/images/launcher_icon/launch.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
#  adaptive_icon_background: "assets/images/launcher_icon/christmas-background.png" # only available for Android 8.0 devices and above
#  adaptive_icon_foreground: "assets/images/launcher_icon/icon-foreground-432x432.png" # only available for Android 8.0 devices and above

# setting splash screen
flutter_native_splash:
  #  Required
  color: "#009ACE"
  image: assets/images/ic_logo.png


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/strings/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/Appicons.ttf

    - family: ArefRuqaa
      fonts:
        - asset: assets/fonts/ArefRuqaa-Regular.ttf
        - asset: assets/fonts/ArefRuqaa-Bold.ttf
          weight: 700

    - family: Almerai
      fonts:
        - asset: assets/fonts/almerai/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/almerai/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/almerai/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/almerai/Almarai-ExtraBold.ttf
          weight: 800